### ISSUE TITLE
🛑 Link Shortener (basic) is down

### ISSUE THREAD

**Issue by HNB0t** [TinDevVN/status#1]
In [`1a51953`](https://github.com/TinDevVN/status/commit/1a519536aee5fa9411321330643b75e382c3f2a3
), Link Shortener (basic) (https://r.tinvn.eu.org) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by hnguyen1910** [comment]
**INFOMATION**: THIS IS JUST A TEST NOTIFICATION.
